### ISSUE TITLE
Upgrade React Native to 0.56.0

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#120]
We want this fix in particular: https://github.com/facebook/react-native/commit/2d9e2f30e17b8e79f2c44ef533ecdd550671304c

We hit facebook/react-native/issues/5787 when building the prod app

**Comment by rahulgi** [comment]
Also, starting Nov 1st, we will not be able to update the app on the Play store unless it targets API version 26 at min, which RNv0.56.0 does do. https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by rahulgi** [comment]
https://facebook.github.io/react-native/docs/upgrading.html
