### ISSUE TITLE
Add notifications when someone send you Raha

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#128]

**Comment by tinaroh** [comment]
Need to store FCM token IDs server-side per device (which is cleared whenever app data is cleared). Didn't research too deeply into what the best practices are here so I tabled this task for now.

* https://medium.com/the-modern-development-stack/react-native-push-notifications-with-firebase-cloud-functions-74b832d45386
* https://github.com/zo0r/react-native-push-notification

**Comment by osdiab** [comment]
Done
