### ISSUE TITLE
Minting referral bonus broken due to member_id/uid inconsistency

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#133]
Writes with uid
https://github.com/rahafoundation/raha-api/blob/354dd725130bdbfbc26db41a5246581665a0712c/src/server/routes/members/index.ts#L293

Reads with member_id
https://github.com/rahafoundation/raha-api/blob/a74f81a54da09e85ba84953188920dc3ef0b76c2/src/server/routes/me/index.ts#L143

**Comment by rahulgi** [comment]
fixxxed.
