### ISSUE TITLE
Avoiding keyboard broken, still covers button

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#231]
When a user clicks on input in the Give form, they should still see the bottom-most button

Broken after app redesign. 
https://github.com/rahafoundation/raha-mobile-app/pull/176

Also fix login -- we also need to avoid keyboard there.

**Comment by markulrich** [comment]
Made very quick fix for it at https://github.com/rahafoundation/raha-mobile-app/pull/259 but we should take a look at how some other apps do SMS login and do better

**Comment by osdiab** [comment]
I will see what I can do now bc I don't like #259

**Comment by osdiab** [comment]
Tryign to repro with simulator since my iphone 6s plus is too big to have this problem lol

**Comment by osdiab** [comment]
ahhh when testing on my simulator it doesn't show the keyboard at all by default. Need to press ⌘K to get that.

Additionally the log in form didn't even have a keyboard avoiding view, which explains why it covered that one.

**Comment by osdiab** [comment]
that said even iphone 6 doesn't have the problem with the keyboard overlapping. what device did you use to repro that? I'm gonna try iPhone 5 now.

**Comment by osdiab** [comment]
Reproduced on both iphone 5 and with large text accessibility sizing.

**Comment by rahulgi** [comment]
#260
