### ISSUE TITLE
Squished faces

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-mobile-app#247]
Everyone is squished in screenshots. We should crop instad of stretch images

**Comment by zkysar** [comment]
Hi Mark

Looking at the thumbnail vs the video: https://photos.app.goo.gl/XhU4aWySNL9hTEvF7. It looks like the video is being properly cropped (You can see less content in thumbnail than in the video) which leads me to believe that these images aren't being squished.

**Comment by rahulgi** [comment]
Hmm, not sure how or when this got fixed, but thanks for investigating, @zkysar!
