### ISSUE TITLE
For Android, let the user know if they have been automatically logged in

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-mobile-app#280]
People tend not to read the "sometimes auto logged in" comment and get very confused if they did not need to enter the text code. We should detect when that happens and add another screen saying "You've been automatically logged in using Google Play Services"

**Comment by tinaroh** [comment]
Yes I'm already on this

**Comment by tinaroh** [comment]
Tabling until tonight since I didn't bring my SIM card.
