### ISSUE TITLE
Error: Video already exists at intended storage location on Verification

### ISSUE THREAD

**Issue by rahulgi** [rahafoundation/raha-mobile-app#287]
Api returns `Error: 400 Bad Request: Video already exists at intended storage destination.`

**Comment by rahulgi** [comment]
Could be b/c the server is expecting a video thumbnail and we're not providing one. @osdiab can you test verification on the latest iOS build and see if that works?

**Comment by tinaroh** [comment]
Set as p0 for now since it might be preventing iOS prod users from recording. Hopefully Apple approves our update soon.

**Comment by rahulgi** [comment]
Patched on the API side by https://github.com/rahafoundation/raha-api/pull/104 and https://github.com/rahafoundation/raha-api/pull/105.
