### ISSUE TITLE
Videos not showing up for new users

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#290]
Mark: just signed up my roommates but I don't see their videos! Tony Li and Jasper Eisenberg

**Comment by rahulgi** [comment]
@markulrich did they sign up on Android or iOS?

**Comment by rahulgi** [comment]
K, their videos should be showing now. Neither was uploaded with thumbnails which leads me to believe they took their videos on iPhones. This issue should be fixed once we get another version of the iOS app released. Closing this issue for now, but let me know if my assumption that they used iPhones is not correct, @markulrich.
