### ISSUE TITLE
Box to enter in your name on iOS appears tiny

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-mobile-app#299]
And it's weird to have both "Enter name:" followed by "Your name here" as a placeholder. Typically I've seen mobile apps only do one or the other for label/placeholder, not both.

**Comment by tinaroh** [comment]
@markulrich  Please see #279 and #294. I believe this issue should be resolved with the latest version of iOS + a CodePush update I'm planning on doing today.

**Comment by tinaroh** [comment]
I don't think we can CodePush to such an old version. I'll push my change once iOS gets approved.
