### ISSUE TITLE
Virtualized List is too large making it slow to update

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-mobile-app#51]

**Comment by markulrich** [comment]
> VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. Object

**Comment by osdiab** [comment]
this seems like a really general issue, we should probably focus on specific poor performance  points like #34

**Comment by rahulgi** [comment]
agreed, editing title to reflect the message that Mark posted.
