### ISSUE TITLE
Deeplink into app

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#76]

**Comment by osdiab** [comment]
Is this complete? @tinaroh

**Comment by tinaroh** [comment]
No, I need to incorporate redirecting people to SMS login before onboarding and HTTPS deeplinks

**Comment by tinaroh** [comment]
Implemented but not enabled until HTTPS/HTTP is complete https://github.com/rahafoundation/raha-mobile-app/issues/119
